# Generated by Django 5.1.3 on 2025-03-21 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('username', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('sso_email', models.EmailField(blank=True, db_column='SSO_EMAIL', max_length=254, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('is_user', models.BooleanField(db_column='IS_USER', default=True)),
                ('is_staff', models.BooleanField(db_column='IS_STAFF', default=False)),
                ('is_superuser', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='DATE_JOINED')),
                ('last_login', models.DateTimeField(db_column='LAST_LOGIN', null=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=255)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('is_deleted', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_column='DELETED_AT', null=True)),
                ('first_name', models.CharField(db_column='FIRST_NAME', max_length=255)),
                ('last_name', models.CharField(db_column='LAST_NAME', max_length=255)),
                ('profile_image_url', models.CharField(blank=True, db_column='PROFILE_IMAGE_URL', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, db_column='DATE_OF_BIRTH')),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=255)),
                ('user', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_DETAILS',
            },
        ),
    ]
